import { supabase } from "@/integrations/supabase/client";

/**
 * Official ULB authority directory (source of truth: uploaded Greater Chennai
 * Corporation dataset). Hierarchy: ULB -> Zone -> Ward -> Councillor.
 * Nothing here is generated by the app; every row carries its official source.
 */

export type Ulb = {
  ulb_id: string;
  ulb_name: string;
  ulb_name_tamil: string;
  ulb_type: string;
  district: string;
  state: string;
  official_source: string;
  source_checked_at: string;
};

export type Zone = {
  zone_id: string;
  ulb_id: string;
  zone_number: number;
  zone_name: string;
  official_source: string;
  source_checked_at: string;
};

export type DirectoryWard = {
  id: string;
  ward_ref: string | null;
  ward_number: number;
  ward_name_en: string;
  ward_name_ta: string;
  zone_id: string | null;
  ulb_id: string | null;
  ward_status: string;
  official_ward_email: string | null;
  official_source: string | null;
  source_checked_at: string | null;
  lat: number | null;
  lng: number | null;
};

export type Councillor = {
  councillor_id: string;
  ward_ref: string;
  ward_uuid: string | null;
  name: string | null;
  designation: string;
  official_contact_phone: string | null;
  official_contact_email: string | null;
  status: string;
  official_source: string;
  source_checked_at: string;
};

export type UlbLeader = {
  authority_id: string;
  ulb_id: string;
  role: string;
  name: string;
  phone: string | null;
  office_phone: string | null;
  email: string | null;
  official_source: string;
  source_checked_at: string;
};

export async function fetchUlbs(): Promise<Ulb[]> {
  const { data } = await supabase.from("ulbs").select("*").order("ulb_name");
  return (data ?? []) as Ulb[];
}

export async function fetchZones(ulbId?: string): Promise<Zone[]> {
  let q = supabase.from("zones").select("*").order("zone_number");
  if (ulbId) q = q.eq("ulb_id", ulbId);
  const { data } = await q;
  return (data ?? []) as Zone[];
}

export async function fetchDirectoryWards(filter?: { ulbId?: string; zoneId?: string }) {
  let q = supabase
    .from("wards")
    .select(
      "id,ward_ref,ward_number,ward_name_en,ward_name_ta,zone_id,ulb_id,ward_status,official_ward_email,official_source,source_checked_at,lat,lng",
    )
    .not("ward_ref", "is", null)
    .order("ward_number");
  if (filter?.ulbId) q = q.eq("ulb_id", filter.ulbId);
  if (filter?.zoneId) q = q.eq("zone_id", filter.zoneId);
  const { data } = await q;
  return (data ?? []) as DirectoryWard[];
}

/** Councillor for a ward. Returns null when the seat has no official record. */
export async function fetchCouncillorForWard(wardRef: string | null): Promise<Councillor | null> {
  if (!wardRef) return null;
  const { data } = await supabase.from("councillors").select("*").eq("ward_ref", wardRef).maybeSingle();
  return (data ?? null) as Councillor | null;
}

export async function fetchLeadership(ulbId: string): Promise<UlbLeader[]> {
  const { data } = await supabase.from("ulb_leadership").select("*").eq("ulb_id", ulbId).order("role");
  return (data ?? []) as UlbLeader[];
}

export async function fetchUlbForWard(ulbId: string | null): Promise<Ulb | null> {
  if (!ulbId) return null;
  const { data } = await supabase.from("ulbs").select("*").eq("ulb_id", ulbId).maybeSingle();
  return (data ?? null) as Ulb | null;
}

export async function fetchZoneById(zoneId: string | null): Promise<Zone | null> {
  if (!zoneId) return null;
  const { data } = await supabase.from("zones").select("*").eq("zone_id", zoneId).maybeSingle();
  return (data ?? null) as Zone | null;
}

export function sourceNote(source: string | null, checkedAt: string | null, lang: "en" | "ta") {
  if (!source) return null;
  const when = checkedAt ? new Date(checkedAt).toLocaleDateString(lang === "ta" ? "ta-IN" : "en-IN") : null;
  return {
    href: source,
    label:
      lang === "ta"
        ? `அதிகாரப்பூர்வ ஆதாரம்${when ? ` · சரிபார்க்கப்பட்டது ${when}` : ""}`
        : `Official source${when ? ` · checked ${when}` : ""}`,
  };
}
